# Generated by Django 3.2.4 on 2021-06-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nazwa')),
                ('slug', models.SlugField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'kategorię',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Numer kortu')),
                ('air_condition', models.BooleanField(default=False, verbose_name='Klimatyzacja')),
                ('lighting', models.BooleanField(default=True, verbose_name='Oświetlenie')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='courts.category', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'kort',
                'verbose_name_plural': 'Korty',
                'ordering': ('number',),
            },
        ),
    ]
