# Generated by Django 3.2.4 on 2021-07-14 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0005_alter_pricelist_hour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ['category', 'weekend', 'time'], 'verbose_name': 'cennik', 'verbose_name_plural': 'Plany cenowe'},
        ),
        migrations.RemoveConstraint(
            model_name='pricelist',
            name='unique_price',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='hour',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='time',
            field=models.IntegerField(blank=True, choices=[(0, datetime.time(0, 0)), (1, datetime.time(1, 0)), (2, datetime.time(2, 0)), (3, datetime.time(3, 0)), (4, datetime.time(4, 0)), (5, datetime.time(5, 0)), (6, datetime.time(6, 0)), (7, datetime.time(7, 0)), (8, datetime.time(8, 0)), (9, datetime.time(9, 0)), (10, datetime.time(10, 0)), (11, datetime.time(11, 0)), (12, datetime.time(12, 0)), (13, datetime.time(13, 0)), (14, datetime.time(14, 0)), (15, datetime.time(15, 0)), (16, datetime.time(16, 0)), (17, datetime.time(17, 0)), (18, datetime.time(18, 0)), (19, datetime.time(19, 0)), (20, datetime.time(20, 0)), (21, datetime.time(21, 0)), (22, datetime.time(22, 0)), (23, datetime.time(23, 0))], null=True, verbose_name='Godzina'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('category', 'weekend', 'time'), name='unique_price'),
        ),
    ]
