# Generated by Django 3.2.4 on 2021-07-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0006_auto_20210714_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='comments',
            new_name='comment',
        ),
    ]
