# Generated by Django 3.2.4 on 2021-07-28 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0007_rename_comments_reservation_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nazwa')),
                ('discount', models.PositiveIntegerField(verbose_name='Zniżka')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='discount',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='courts.discount', verbose_name='Zniżka'),
        ),
    ]
