# Generated by Django 3.2.4 on 2021-08-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0008_auto_20210728_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'zniżka', 'verbose_name_plural': 'Zniżki'},
        ),
        migrations.AddField(
            model_name='discount',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='courts.category', verbose_name='Kategoria'),
            preserve_default=False,
        ),
    ]
