# Generated by Django 3.2.4 on 2021-08-06 16:57

import courts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0009_auto_20210805_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='number',
            field=courts.fields.OrderField(blank=True, unique=True, verbose_name='Numer kortu'),
        ),
    ]
