# Generated by Django 3.2.4 on 2021-08-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0010_alter_court_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ('order',), 'verbose_name': 'kort', 'verbose_name_plural': 'Korty'},
        ),
        migrations.RenameField(
            model_name='court',
            old_name='number',
            new_name='order',
        ),
    ]
